//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_usuario()
        {
            this.inv_ubicacion = new HashSet<inv_ubicacion>();
        }
    
        public int usr_id { get; set; }
        public string usr_usuario { get; set; }
        public string usr_password { get; set; }
        public string usr_nombre { get; set; }
        public System.DateTime usr_fecha_tran { get; set; }
        public int usr_usuario_tran { get; set; }
        public bool usr_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_ubicacion> inv_ubicacion { get; set; }
    }
}
