//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cxc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fac_cxc()
        {
            this.fac_cxc_detalle = new HashSet<fac_cxc_detalle>();
        }
    
        public int cxc_id { get; set; }
        public Nullable<System.DateTime> cxc_fecha { get; set; }
        public Nullable<int> cxc_factura { get; set; }
        public Nullable<int> cxc_cliente { get; set; }
        public Nullable<decimal> cxc_monto { get; set; }
        public Nullable<int> cxc_dias_credito { get; set; }
        public Nullable<System.DateTime> cxc_fecha_trans { get; set; }
        public Nullable<int> cxc_usuario_trans { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fac_cxc_detalle> fac_cxc_detalle { get; set; }
    }
}
