//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_factura_detalle
    {
        public int fde_id { get; set; }
        public Nullable<int> fde_factura { get; set; }
        public string fde_producto { get; set; }
        public string fde_descripcion { get; set; }
        public Nullable<int> fde_cantidad { get; set; }
        public string fde_unidad_medida { get; set; }
        public Nullable<decimal> fde_precio_unitario { get; set; }
        public Nullable<decimal> fde_descuento_porcen { get; set; }
        public Nullable<decimal> fde_descuento_monto { get; set; }
        public Nullable<decimal> fde_costo { get; set; }
        public Nullable<int> fde_usuario_tran { get; set; }
        public Nullable<System.DateTime> fde_fecha_tran { get; set; }
    
        public virtual fac_factura fac_factura { get; set; }
    }
}
