//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_tipo_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fac_tipo_pago()
        {
            this.fac_factura = new HashSet<fac_factura>();
        }
    
        public int tpa_id { get; set; }
        public string tpa_tipo_pago { get; set; }
        public int tpa_num_dias { get; set; }
        public bool tpa_eliminado { get; set; }
        public Nullable<int> tpa_usuario_tran { get; set; }
        public Nullable<System.DateTime> tpa_fecha_tran { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fac_factura> fac_factura { get; set; }
    }
}
