//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cliente
    {
        public int cli_id { get; set; }
        public string cli_nombres { get; set; }
        public string cli_direccion { get; set; }
        public string cli_no_registro { get; set; }
        public string cli_telefono { get; set; }
        public bool cli_activo { get; set; }
        public System.DateTime cli_fecha_tran { get; set; }
        public int cli_usuario_tran { get; set; }
        public int cli_eliminado { get; set; }
    }
}
