//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_pedido_detalle
    {
        public int pde_id { get; set; }
        public Nullable<int> pde_pedido { get; set; }
        public Nullable<int> pde_cantidad { get; set; }
        public Nullable<int> pde_producto { get; set; }
        public Nullable<decimal> pde_precio_uni { get; set; }
        public Nullable<decimal> pde_descuento_porcen { get; set; }
        public Nullable<decimal> fde_descuento_monto { get; set; }
        public Nullable<decimal> pde_costo { get; set; }
        public Nullable<bool> pde_eliminado { get; set; }
        public Nullable<int> pde_usuario_tran { get; set; }
        public Nullable<System.DateTime> pde_fecha_tran { get; set; }
    
        public virtual fac_pedido fac_pedido { get; set; }
    }
}
