//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_precio_detalle
    {
        public int pde_id { get; set; }
        public Nullable<int> pde_precio { get; set; }
        public Nullable<int> pde_producto { get; set; }
        public Nullable<decimal> pde_valor { get; set; }
        public Nullable<bool> pde_activo { get; set; }
        public Nullable<System.DateTime> pde_fecha_tran { get; set; }
        public Nullable<int> pde_usuario_tran { get; set; }
    
        public virtual fac_precio fac_precio { get; set; }
    }
}
