//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fac_factura()
        {
            this.fac_factura_detalle = new HashSet<fac_factura_detalle>();
        }
    
        public int fac_id { get; set; }
        public string fac_serie { get; set; }
        public int fac_tipo_factura { get; set; }
        public int fac_tipo_pago { get; set; }
        public Nullable<int> fac_caja { get; set; }
        public System.DateTime fac_fecha { get; set; }
        public int fac_numero { get; set; }
        public string fac_no_registro { get; set; }
        public string fac_cliente { get; set; }
        public Nullable<int> fac_vendedor { get; set; }
        public Nullable<decimal> fac_monto { get; set; }
        public Nullable<decimal> fac_impuesto { get; set; }
        public Nullable<decimal> fac_total { get; set; }
        public string fac_nota { get; set; }
        public Nullable<bool> fac_eliminado { get; set; }
        public Nullable<int> fac_usuario_tran { get; set; }
        public Nullable<System.DateTime> fac_fecha_tran { get; set; }
        public Nullable<int> fac_id_cliente { get; set; }
        public Nullable<decimal> fac_retension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fac_factura_detalle> fac_factura_detalle { get; set; }
        public virtual fac_tipo_factura fac_tipo_factura1 { get; set; }
        public virtual fac_tipo_pago fac_tipo_pago1 { get; set; }
        public virtual fac_vendedor fac_vendedor1 { get; set; }
        public virtual fac_cliente fac_cliente1 { get; set; }
    }
}
