//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_producto_stock
    {
        public int sto_id { get; set; }
        public int sto_cantidad { get; set; }
        public int sto_producto { get; set; }
        public Nullable<int> sto_ubicacion { get; set; }
        public decimal sto_costo { get; set; }
        public System.DateTime sto_fecha_tran { get; set; }
        public int sto_usuario_tran { get; set; }
        public bool sto_eliminado { get; set; }
    
        public virtual inv_producto inv_producto { get; set; }
        public virtual inv_ubicacion inv_ubicacion { get; set; }
    }
}
