//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_despacho_detalle
    {
        public int ddt_id { get; set; }
        public int ddt_despacho { get; set; }
        public int ddt_cantidad { get; set; }
        public int ddt_producto { get; set; }
        public string ddt_descripcion { get; set; }
        public Nullable<decimal> ddt_costo { get; set; }
        public Nullable<int> ddt_ubicacion { get; set; }
        public System.DateTime ddt_fecha_tran { get; set; }
        public int ddt_usuario_tran { get; set; }
        public bool ddt_eliminado { get; set; }
    
        public virtual inv_despacho inv_despacho { get; set; }
    }
}
