//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_despacho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_despacho()
        {
            this.inv_despacho_detalle = new HashSet<inv_despacho_detalle>();
        }
    
        public int des_id { get; set; }
        public int des_factura { get; set; }
        public System.DateTime des_fecha { get; set; }
        public string des_cliente { get; set; }
        public string des_direccion { get; set; }
        public Nullable<bool> des_aplicado { get; set; }
        public string des_comentario { get; set; }
        public System.DateTime des_fecha_tran { get; set; }
        public int des_usuario_tran { get; set; }
        public bool des_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_despacho_detalle> inv_despacho_detalle { get; set; }
    }
}
