//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_trans_detalle
    {
        public int tde_id { get; set; }
        public int tde_trans { get; set; }
        public Nullable<int> tde_cantidad { get; set; }
        public Nullable<int> tde_producto { get; set; }
        public string tde_descripcion { get; set; }
        public Nullable<decimal> tde_costo { get; set; }
        public Nullable<int> tde_ubicacion { get; set; }
        public Nullable<System.DateTime> tde_fecha_trans { get; set; }
        public Nullable<int> tde_usuario_trans { get; set; }
        public Nullable<bool> tde_eliminado { get; set; }
    
        public virtual inv_producto inv_producto { get; set; }
        public virtual inv_trans inv_trans { get; set; }
        public virtual inv_ubicacion inv_ubicacion { get; set; }
    }
}
