//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_trans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_trans()
        {
            this.inv_trans_detalle = new HashSet<inv_trans_detalle>();
        }
    
        public int tra_id { get; set; }
        public Nullable<System.DateTime> tra_fecha { get; set; }
        public string tra_usuario { get; set; }
        public Nullable<int> tra_tipo { get; set; }
        public string tra_comentario { get; set; }
        public Nullable<System.DateTime> tra_fecha_trans { get; set; }
        public Nullable<int> tra_usuario_trans { get; set; }
        public Nullable<bool> tra_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_trans_detalle> inv_trans_detalle { get; set; }
    }
}
