//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_proveedor()
        {
            this.inv_producto = new HashSet<inv_producto>();
        }
    
        public int prv_id { get; set; }
        public string prv_nombre { get; set; }
        public string prv_direccion { get; set; }
        public string prv_telefono { get; set; }
        public System.DateTime prv_fecha_trans { get; set; }
        public int prv_usuario_trans { get; set; }
        public bool prv_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_producto> inv_producto { get; set; }
    }
}
