//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_producto_tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inv_producto_tipo()
        {
            this.inv_producto = new HashSet<inv_producto>();
        }
    
        public int pti_id { get; set; }
        public string pti_descripcion { get; set; }
        public Nullable<bool> pti_visible { get; set; }
        public System.DateTime pti_fecha_tran { get; set; }
        public int pti_usuario_tran { get; set; }
        public bool pti_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv_producto> inv_producto { get; set; }
    }
}
